port: 8000

postURL: http://localhost:8001

# tracing provides configuration for OpenTelemetry
tracing:
  # provider is the provider name. Currently, stdout, jaegar and zipkin are supported.
  provider: "stdout"

  # skipTraceExport only applies when provider is stdout. Set skipTraceExport to true
  # so that trace information is not written to stdout.
  skipTraceExport: true

  # endpoint is where trace information should be routed. Applies to zipkin and jaegar.
  # endpoint: "http://localhost:9411/api/v2/spans"